#ifndef COMMANDS_H
#    define COMMANDS_H
#    include "types/types.h"

#    define MAKRO_COMMAND_PROTOTYPE(NAME_COMMANDS)                            \
        void command_do_##NAME_COMMANDS(                                      \
            struct pdp_11_t *, address_word_t, word_t, byte_t)

struct pdp_11_t;

void __command_reg_dump(struct pdp_11_t *pdp);

void set_flag_C(word_t);
void set_flag_NZ(word_t);
void set_flag_V(word_t);

MAKRO_COMMAND_PROTOTYPE(halt);
MAKRO_COMMAND_PROTOTYPE(add);
MAKRO_COMMAND_PROTOTYPE(mov);
MAKRO_COMMAND_PROTOTYPE(movb);
MAKRO_COMMAND_PROTOTYPE(inc);
MAKRO_COMMAND_PROTOTYPE(sob);

MAKRO_COMMAND_PROTOTYPE(clr);
MAKRO_COMMAND_PROTOTYPE(unknown);
MAKRO_COMMAND_PROTOTYPE(adcb);

MAKRO_COMMAND_PROTOTYPE(br);
MAKRO_COMMAND_PROTOTYPE(beq);

MAKRO_COMMAND_PROTOTYPE(bpl);
MAKRO_COMMAND_PROTOTYPE(tstb);

MAKRO_COMMAND_PROTOTYPE(jsr);
MAKRO_COMMAND_PROTOTYPE(rts);

MAKRO_COMMAND_PROTOTYPE(tst);

MAKRO_COMMAND_PROTOTYPE(adc);
MAKRO_COMMAND_PROTOTYPE(ash);
MAKRO_COMMAND_PROTOTYPE(ashc);
MAKRO_COMMAND_PROTOTYPE(asl);
MAKRO_COMMAND_PROTOTYPE(aslb);
MAKRO_COMMAND_PROTOTYPE(asr);
MAKRO_COMMAND_PROTOTYPE(asrb);
MAKRO_COMMAND_PROTOTYPE(com);
MAKRO_COMMAND_PROTOTYPE(comb);
MAKRO_COMMAND_PROTOTYPE(div);

MAKRO_COMMAND_PROTOTYPE(jmp);
MAKRO_COMMAND_PROTOTYPE(mul);

MAKRO_COMMAND_PROTOTYPE(rol);
MAKRO_COMMAND_PROTOTYPE(rolb);

MAKRO_COMMAND_PROTOTYPE(ror);
MAKRO_COMMAND_PROTOTYPE(rorb);

#endif // COMMANDS_H
#pragma once
